"""Broker message code groups owned by connection supervisors."""

from __future__ import annotations

BROKER_CONNECTIVITY_LOST_CODES = frozenset({1100, 2110})
LIVE_UPDATE_FAILURE_CODE = 10182
WEAK_DATA_FARM_CODES = frozenset(
    {2103, 2105, 2157, LIVE_UPDATE_FAILURE_CODE, 2104, 2106, 2158}
)
DATA_LOST_CODE = 1101
DATA_MAINTAINED_CODE = 1102
SOCKET_RESET_CODE = 1300

SUPERVISOR_OWNED_BROKER_CODES = (
    BROKER_CONNECTIVITY_LOST_CODES
    | WEAK_DATA_FARM_CODES
    | {DATA_LOST_CODE, DATA_MAINTAINED_CODE, SOCKET_RESET_CODE}
)
