from datetime import datetime, timezone
from zoneinfo import ZoneInfo

import ib_insync as ibi
import pytest

from haymaker.contract_registry import DetailsContainer
from haymaker.details_processor import (
    Details,
    is_active,
    next_active,
    process_trading_hours,
    typical_session_length,
)

trading_hours_string = "20231016:1700-20231017:1600;20231017:1700-20231018:1600;20231018:1700-20231019:1600;20231019:1700-20231020:1600;20231021:CLOSED;20231022:1700-20231023:1600"  # noqa


def test_process_trading_hours_returns_no_errors():
    assert isinstance(process_trading_hours(trading_hours_string), list)


def test_process_trading_hours():
    """
    Output generated by `proces_trading_hours` in Eastern compared to
    output given in UTC.
    """
    output = [
        (
            datetime(2023, 10, 16, 17, 00, tzinfo=timezone.utc),
            datetime(2023, 10, 17, 16, 00, tzinfo=timezone.utc),
        ),
        (
            datetime(2023, 10, 17, 17, 00, tzinfo=timezone.utc),
            datetime(2023, 10, 18, 16, 00, tzinfo=timezone.utc),
        ),
        (
            datetime(2023, 10, 18, 17, 00, tzinfo=timezone.utc),
            datetime(2023, 10, 19, 16, 00, tzinfo=timezone.utc),
        ),
        (
            datetime(2023, 10, 19, 17, 00, tzinfo=timezone.utc),
            datetime(2023, 10, 20, 16, 00, tzinfo=timezone.utc),
        ),
        # non trading day is just skipped
        (
            datetime(2023, 10, 22, 17, 00, tzinfo=timezone.utc),
            datetime(2023, 10, 23, 16, 00, tzinfo=timezone.utc),
        ),
    ]
    assert (
        process_trading_hours(
            trading_hours_string, input_tz="UTC", output_tz="US/Eastern"
        )
        == output
    )


@pytest.mark.parametrize(
    "datetimetuple,result",
    [
        ((2023, 10, 16, 17, 15), True),  # from first tuple
        ((2023, 10, 17, 20, 15), True),  # from non-first tuple
        ((2023, 10, 17, 16, 30), False),  # during daily off hours
        ((2023, 10, 21, 17, 15), False),  # during closed day]
    ],
)
def test_is_active(datetimetuple: tuple[int, int, int, int, int], result: bool):
    # hours output in UTC, which compares correctly with now given in US/Central
    hours = process_trading_hours(trading_hours_string, input_tz="US/Central")
    now = datetime(*datetimetuple, tzinfo=ZoneInfo("US/Central"))
    assert is_active(hours, now=now) == result


@pytest.mark.parametrize(
    "datetimetuple,result",
    [
        (
            (2023, 10, 16, 17, 15),
            (2023, 10, 17, 17, 00),
        ),  # from first tuple, market is active
        (
            (2023, 10, 17, 20, 15),
            (2023, 10, 18, 17, 00),
        ),  # from non-first tuple, market is active
        ((2023, 10, 17, 16, 30), (2023, 10, 17, 17, 00)),  # during daily off hours
        ((2023, 10, 21, 17, 15), (2023, 10, 22, 17, 00)),  # during closed day]
    ],
)
def test_next_active(
    datetimetuple: tuple[int, int, int, int, int],
    result: tuple[int, int, int, int, int],
):
    hours = process_trading_hours(
        trading_hours_string,
    )
    now = datetime(*datetimetuple, tzinfo=ZoneInfo("US/Central"))
    assert next_active(hours, now=now) == datetime(
        *result, tzinfo=ZoneInfo("US/Central")
    )


def test_process_trading_hours_accepts_empty_string():
    # this is what IB returns for an expired contract
    assert isinstance(process_trading_hours("", ""), list)


def test_is_active_for_expired_contract():
    trading_hours = process_trading_hours("", input_tz="")
    assert is_active(trading_hours) is False


def test_process_trading_hours_for_expired_contracts():
    assert process_trading_hours("", "") == []


def test_next_active_for_expired_contracts():
    trading_hours = process_trading_hours("", input_tz="")
    assert next_active(trading_hours) is None


def test_typical_session_length():
    time_tuples = process_trading_hours(trading_hours_string)
    typical_delta = typical_session_length(time_tuples)
    assert typical_delta.total_seconds() == 23 * 60 * 60


def test_details_wrapped_in_Details_object(details):
    container = DetailsContainer()
    container[details.contract] = details
    assert isinstance(container[details.contract], Details)


class TestAtomDetails:
    @pytest.fixture
    def details_object(self, details: ibi.ContractDetails):
        do = Details(details)
        yield do

    def test_trading_hours_processed(
        self, details_object: Details, details: ibi.ContractDetails
    ):
        assert isinstance(details_object.trading_hours, list)  # type: ignore

    def test_trading_hours_is_open(
        self, details_object: Details, details: ibi.ContractDetails
    ):
        assert isinstance(details_object.is_open(), bool)  # type: ignore


def test_details_work_for_expired_contracts():
    # input details directly copied from the system
    input_details = ibi.ContractDetails(
        contract=ibi.Contract(
            secType="FUT",
            conId=563947728,
            symbol="NQ",
            lastTradeDateOrContractMonth="20231215",
            multiplier="20",
            exchange="CME",
            currency="USD",
            localSymbol="NQZ3",
            tradingClass="NQ",
        ),
        marketName="NQ",
        minTick=0.25,
        orderTypes="LTH",
        validExchanges="CME,QBALGO",
        priceMagnifier=1,
        underConId=11004958,
        longName="E-mini NASDAQ 100 ",
        contractMonth="202312",
        industry="",
        category="",
        subcategory="",
        timeZoneId="",
        tradingHours="",
        liquidHours="",
        evRule="",
        evMultiplier=0,
        mdSizeMultiplier=1,
        aggGroup=2147483647,
        underSymbol="NQ",
        underSecType="IND",
        marketRuleIds="67,67",
        secIdList=[],
        realExpirationDate="20231215",
        lastTradeTime="",
        stockType="",
        minSize=1.0,
        sizeIncrement=1.0,
        suggestedSizeIncrement=1.0,
        cusip="",
        ratings="",
        descAppend="",
        bondType="",
        couponType="",
        callable=False,
        putable=False,
        coupon=0,
        convertible=False,
        maturity="",
        issueDate="",
        nextOptionDate="",
        nextOptionType="",
        nextOptionPartial=False,
        notes="",
    )
    d = Details(input_details)
    assert d.is_open() is False
    assert d.is_liquid() is False
    assert d.next_open() is None
