from ._daterange import DateRange as DateRange
from ._generalslice import CLOSED_CLOSED as CLOSED_CLOSED, CLOSED_OPEN as CLOSED_OPEN, OPEN_CLOSED as OPEN_CLOSED, OPEN_OPEN as OPEN_OPEN
from ._mktz import mktz as mktz
from ._parse import parse as parse
from _typeshed import Incomplete

long = int
Ranges: Incomplete

def string_to_daterange(str_range, delimiter: str = ..., as_dates: bool = ..., interval=...): ...
def to_dt(date, default_tz: Incomplete | None = ...): ...
def to_pandas_closed_closed(date_range, add_tz: bool = ...): ...
def ms_to_datetime(ms, tzinfo: Incomplete | None = ...): ...
def _add_tzone(dtm): ...
def datetime_to_ms(d): ...
def utc_dt_to_local_dt(dtm): ...
