from ._config import BENCHMARK_MODE as BENCHMARK_MODE, ENABLE_PARALLEL as ENABLE_PARALLEL, LZ4_HIGH_COMPRESSION as LZ4_HIGH_COMPRESSION, LZ4_MINSZ_PARALLEL as LZ4_MINSZ_PARALLEL, LZ4_N_PARALLEL as LZ4_N_PARALLEL, LZ4_WORKERS as LZ4_WORKERS
from _typeshed import Incomplete

lz4_compressHC: Incomplete
logger: Incomplete
_compress_thread_pool: Incomplete

def enable_parallel_lz4(mode) -> None: ...
def set_compression_pool_size(pool_size) -> None: ...
def compress_array(str_list, withHC=...): ...
def compress(_str): ...
def compressHC(_str): ...
def compressHC_array(str_list): ...
def decompress(_str): ...
def decompress_array(str_list): ...
