from ._config import FW_POINTERS_CONFIG_KEY as FW_POINTERS_CONFIG_KEY, FwPointersCfg as FwPointersCfg
from _typeshed import Incomplete

logger: Incomplete
NP_OBJECT_DTYPE: Incomplete
_use_new_count_api: Incomplete

def get_fwptr_config(version): ...
def _detect_new_count_api(): ...
def indent(s, num_spaces): ...
def are_equals(o1, o2, **kwargs): ...
def enable_sharding(arctic, library_name, hashed: bool = ..., key: str = ...) -> None: ...
def mongo_count(collection, filter: Incomplete | None = ..., **kwargs): ...
