from .date import mktz as mktz
from _typeshed import Incomplete

PD_VER: Incomplete
logger: Incomplete

def fancy_group_by(df, grouping_level: int = ..., aggregate_level: int = ..., method: str = ..., max_: Incomplete | None = ..., min_: Incomplete | None = ..., within: Incomplete | None = ...): ...
def groupby_asof(df, as_of: Incomplete | None = ..., dt_col: str = ..., asof_col: str = ...): ...
def multi_index_insert_row(df, index_row, values_row): ...
def insert_at(df, sample_date, values): ...
