source: contracts.csv
barSize: &barSize 30 secs
wts: &wts TRADES
max_bars: 100_000 # max number of bars pulled in one request
max_period: 120 # max duration of downloaded data in days
run_mode: "reconnect"
number_of_workers: 20
fill_gaps: False
auto_save_interval: 900 # in secs, zero=off
worker_timeout: 60
pacer_restrictions:
  - !!python/tuple [5, 2] # [max requests, seconds]
  - !!python/tuple [60, 600]
pacer_no_restriction: False # toggle to quickly switch off pacer (will ignore previous item)

# ---- futures config ----
# contfuture, fullchain, current, exact, current_and_expired, current_and_contfuture
# current_and_expired is default; it will collect all available history
# that has not already been collected
futures_selector: "current_and_expired"
# TODO: needs to be tested
futures_fullchain_spec: full #  full, active, expired; which contracts should be included in futures fullchain; relevant only if futureshow==fullchain;
futures_current_index: 0 #  zero->current contfuture, positive index->future, negative->past; which contract is considered current; relevant only if futures_selector==current;
# ---- end futures config ----

# if the file is overriden, make sure that `wts` and `barSize` refer to the intended copy
datastore:
  !!python/object/apply:haymaker.datastore.ArcticStore
  # joins previuosly defined aliases to create collection name
  - !!python/object/apply:haymaker.utilities.strjoin
    - *wts
    - _
    - *barSize
logging_config: "dataloader_logging_config.yaml"
