source: contracts.csv
barSize: &barSize 30 secs
wts: &wts TRADES
aggression: 1
watchdog: False
max_number_of_workers: 40
fill_gaps: False
auto_save_interval: 900 # in secs, zero=off
pacer_restrictions:
  - !!python/tuple [5, 2] # [max requests, seconds]
  - !!python/tuple [60, 600]
pacer_no_restriction: False # toggle to quickly switch off pacer (will ignore previous item)

# ---- futures config ----
futures_selector: "contfuture" # contfuture, fullchain, current, exact, current_and_contfuture
# TODO: needs to be tested
futures_fullchain_spec: full #  full, active, expired; which contracts should be included in futures fullchain; relevant only if futureshow==fullchain;
futures_current_index: 0 #  zero->current contfuture, positive index->future, negative->past; which contract is considered current; relevant only if futures_selector==current;
# ---- end futures config ----

# if the file is overriden, make sure that `wts` and `barSize` refer to the intended copy
datastore:
  !!python/object/apply:haymaker.datastore.ArcticStore
  # joins previuosly defined aliases to create collection name
  - !!python/object/apply:haymaker.utilities.strjoin
    - *wts
    - _
    - *barSize
logging_config: "dataloader_logging_config.yaml"
