connection:
  client_id: 1
  app_timeout: 600

logging:
  config_file: dataloader_logging_config.yaml

storage:
  base_directory: ib_data
  mongodb:
    client:
      host: localhost
      port: 27017
    database: null
  block_library: null
  market_data_library: market_data
  dataframe_save_frequency: 900

download: {}

pacing: {}

futures: {}
