"""Discoverable public toolbox of pre-built Haymaker trading components."""

from .aggregators import (
    BarAggregator,
    CountBars,
    DfAggregator,
    NoFilter,
    TickBars,
    TimeBars,
    VolumeBars,
    VolumeGrouper,
)
from .bracket_legs import (
    AbstractBracketLeg,
    AdjustableFixedTrailingStop,
    AdjustableTrailingFixedStop,
    AdjustableTrailingStop,
    FixedStop,
    FlexibleTakeProfitAsStopMultiple,
    TakeProfitAsStopMultiple,
    TrailingStop,
)
from .execution_models import (
    BracketExecutionModel,
    ExecutionModel,
    SerialTargetExecutionModel,
)
from .execution_router import (
    ExecutionRouter,
    ExecutionRule,
    contract_is,
    exchange_is,
    security_type_is,
    symbol_is,
    where,
)
from .messages import (
    PositionIntent,
    PositionProposal,
    PositionTarget,
    Signal,
    SignalPair,
    SignalType,
    StandardOrderRole,
)
from .portfolio import (
    FixedSizeAllocator,
    Portfolio,
    PortfolioWrapper,
    PositionAllocator,
)
from .signal_models import PandasSignalModel, SignalModel, read_signal_audit
from .signal_processors import (
    BinaryEntryExitSignalProcessor,
    BinarySignalProcessor,
    OpposingSignalPolicy,
)
from .streamers import (
    HistoricalDataStreamer,
    MktDataStreamer,
    RealTimeBarsStreamer,
    Streamer,
    TickByTickStreamer,
    bar_filter,
)

__all__ = [
    "AbstractBracketLeg",
    "AdjustableFixedTrailingStop",
    "AdjustableTrailingFixedStop",
    "AdjustableTrailingStop",
    "BarAggregator",
    "BinaryEntryExitSignalProcessor",
    "BinarySignalProcessor",
    "BracketExecutionModel",
    "CountBars",
    "DfAggregator",
    "ExecutionModel",
    "ExecutionRouter",
    "ExecutionRule",
    "FixedSizeAllocator",
    "FixedStop",
    "FlexibleTakeProfitAsStopMultiple",
    "HistoricalDataStreamer",
    "MktDataStreamer",
    "NoFilter",
    "OpposingSignalPolicy",
    "PandasSignalModel",
    "PositionIntent",
    "PositionAllocator",
    "PositionProposal",
    "PositionTarget",
    "Portfolio",
    "PortfolioWrapper",
    "RealTimeBarsStreamer",
    "SerialTargetExecutionModel",
    "Signal",
    "SignalPair",
    "SignalModel",
    "SignalType",
    "StandardOrderRole",
    "Streamer",
    "TakeProfitAsStopMultiple",
    "TickBars",
    "TickByTickStreamer",
    "TimeBars",
    "TrailingStop",
    "VolumeBars",
    "VolumeGrouper",
    "bar_filter",
    "contract_is",
    "exchange_is",
    "read_signal_audit",
    "security_type_is",
    "symbol_is",
    "where",
]
