version: 1
disable_existing_loggers: false


formatters:
  default:
    (): ib_tools.logging.setup.UTCFormatter
    format:  "%(asctime)s | %(levelname)-8s | %(name)-23s | %(message)s | %(module)s %(funcName)s %(lineno)d"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  file:
    (): ib_tools.logging.setup.file_setup
    level: DEBUG
    formatter: default
    delay: true
      
loggers:
  ib_tools:
    level: DEBUG
    handlers: [console, file]

