version: 1
disable_existing_loggers: false


formatters:
  default:
    (): ib_tools.logging.setup.UTCFormatter
    format:  "%(asctime)s | %(levelname)-8s | %(name)-23s | %(message)s | %(module)s %(funcName)s %(lineno)d"

handlers:
  console:
    class: logging.StreamHandler
    level: 5
    formatter: default
    stream: ext://sys.stdout


  timed_rotating_file: &file
    (): ib_tools.logging.setup.timed_rotating_file_setup
    level: 5
    formatter: default
    filename: haymakerLog.log
    dirname: "/"
    when: midnight

  timed_rotating_file_specific:
    <<: *file
    filename: strategies.log
    
loggers:
  ib_tools:
    level: 5
    handlers: [console, timed_rotating_file]
  strategy:
    level: DEBUG
    handlers: [timed_rotating_file_specific]
    
