restart_time: 30 # after disconnection, time to wait before reconnection attempt
host: 127.0.0.1
port: 4002
clientId: 0 # do not change
appStartupTime: 0
appTimeout: 20
retryDelay: 2
probeContract:
  !!python/object/apply:ib_insync.Forex
  - EURUSD
probeTimeout: 4

# Controller config:
use_blotter: True
coldstart: False
log_IB_events: False

# These are default order params that will be used by every execution model
# unless different orders are passes to exec model __init__
open_order:
  algoStrategy: Adaptive
  algoParams:
  - !!python/object/apply:ib_insync.TagValue
      - adaptivePriority
      - Normal
  tif: Day
  outsideRth: True
    
close_order:
  tif: GTC
  outsideRth: True
    
stop_order:
  outsideRth: True
  tif: GTC

tp_order:
  # don't use adaptive orders here as not compliant with OCA
  outsideRth: True
  
# all linked orders will use this oca_type (as per IB definition)
oca_type: 1

streamers:
  timeout:
    debug: False
    timeout: 300

# consider making this a dict of params passed to blotter to instantiate the class
blotter_saver:
  class: CsvSaver
  kwds:
    folder: blotter
    name: blotter
    timestamp: False
  # alternative:
  # args: []
  # kwds: {folder: blotter, note: blotter}
  # !!python/object/apply:ib_tools.saver.MongoSaver
  # kwds: {collection: blotter}

# All savers saving to files will create sub-directories here:
data_folder:
  ib_data # folder inside home folder, will be created if doesn't exist
  
ArcticSaver:
  host: localhost
  library: test_log
  
MongoSaver:
  host: localhost
  port: 27017
  db: test_data

dataloader:
  file: contracts.csv
  barSize: 30secs
  wts: TRADES
  aggression: 2
  continuous_futures_only: True
  watchdog: False

  

  
  



