source: contracts.csv
barSize: &barSize 30 secs
wts: &wts TRADES
aggression: 2
continuous_futures_only: True
watchdog: False
max_number_of_workers: 40
fill_gaps: False

datastore:
  !!python/object/apply:ib_tools.datastore.ArcticStore
  # joins previuosly defined aliases to create collection name
  - !!python/object/apply:ib_tools.utilities.strjoin
    - *wts
    - _
    - *barSize

