source: contracts.csv
barSize: &barSize 30 secs
wts: &wts TRADES
aggression: 1
continuous_futures_only: True
watchdog: False
max_number_of_workers: 40
fill_gaps: False
auto_save_interval: 900 # in secs, zero=off
pacer_restrictions:
  - !!python/tuple [2, 6] # [seconds, max requests]
  - !!python/tuple [600, 60]
pacer_no_restriction: False # toggle to quickly switch off pacer in spite of previous item
# ---- futures config ----
futures_selector: "contfuture" # contfuture, fullchain, current, exact 
futures_fullchain_spec: full #  full, active, expired; which contracts should be included in futures fullchain; relevant only if futureshow==fullchain;
futures_current_index: 0 #  zero->current contfuture, positive index->future, negative->past; which contract is considered current; relevant only if futures_selector==current;
# ---- end futures config ----
datastore:
  !!python/object/apply:ib_tools.datastore.ArcticStore
  # joins previuosly defined aliases to create collection name
  - !!python/object/apply:ib_tools.utilities.strjoin
    - *wts
    - _
    - *barSize

