START: str
END: str

class Chunker:
    def to_chunks(self, data, **kwargs) -> None: ...
    def to_range(self, start, end) -> None: ...
    def to_mongo(self, range_obj) -> None: ...
    def filter(self, data, range_obj) -> None: ...
    def exclude(self, data, range_obj) -> None: ...
    def chunk_to_str(self, chunk_id) -> None: ...
