from ._chunker import Chunker as Chunker, END as END, START as START
from _typeshed import Incomplete
from arctic.date import DateRange as DateRange, to_pandas_closed_closed as to_pandas_closed_closed
from collections.abc import Generator

class DateChunker(Chunker):
    TYPE: str
    def to_chunks(self, df, chunk_size: str = ..., func: Incomplete | None = ..., **kwargs) -> Generator[Incomplete, None, None]: ...
    def to_range(self, start, end): ...
    def chunk_to_str(self, chunk_id): ...
    def to_mongo(self, range_obj): ...
    def filter(self, data, range_obj): ...
    def exclude(self, data, range_obj): ...
