"""Compatibility facade for research indicators.

The canonical implementations live under :mod:`haymaker.research.indicators`.
Importing from ``haymaker.indicators`` is kept for live strategies and older
notebooks.
"""

from .research.indicators import (
    adx,
    atr,
    breakout,
    breakout_blip,
    carver,
    chande_momentum_indicator,
    chande_ranking,
    combine_signals,
    crosser,
    divergence_index,
    downsampled_atr,
    downsampled_func,
    extreme_reversal_blip,
    inout_range,
    join_swing,
    macd,
    min_max_blip,
    min_max_index,
    mmean,
    momentum,
    range_blip,
    resample,
    rolling_weighted_mean,
    rolling_weighted_std,
    rsi,
    signal_generator,
    spread,
    strength_oscillator,
    true_sharpe,
    true_range,
    tsi,
    weighted_resample,
    weighted_zscore,
)

__all__ = [
    "adx",
    "atr",
    "breakout",
    "breakout_blip",
    "carver",
    "chande_momentum_indicator",
    "chande_ranking",
    "combine_signals",
    "crosser",
    "divergence_index",
    "downsampled_atr",
    "downsampled_func",
    "extreme_reversal_blip",
    "inout_range",
    "join_swing",
    "macd",
    "min_max_blip",
    "min_max_index",
    "mmean",
    "momentum",
    "range_blip",
    "resample",
    "rolling_weighted_mean",
    "rolling_weighted_std",
    "rsi",
    "signal_generator",
    "spread",
    "strength_oscillator",
    "true_sharpe",
    "true_range",
    "tsi",
    "weighted_resample",
    "weighted_zscore",
]
