from __future__ import annotations

import asyncio
import itertools
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from functools import cache, cached_property
from typing import Awaitable, ClassVar

import eventkit as ev  # type: ignore
import ib_insync as ibi

from .base import Atom
from .config import CONFIG
from .databases import get_mongo_client
from .datastore import AsyncArcticStore
from .details_processor import typical_session_length
from .durationStr_converters import (
    datapoints_to_durationStr,
    date_to_delta_wrapper,
)
from .timeout import Timeout

log = logging.getLogger(__name__)


_counter = itertools.count().__next__

MARKET_DATA_LIB_NAME = CONFIG.get("market_data_lib", "market_data")


@cache
def get_store():
    return (
        AsyncArcticStore(lib=MARKET_DATA_LIB_NAME, host=get_mongo_client())
        if MARKET_DATA_LIB_NAME
        else None
    )


def last_db_point(
    contract: ibi.Contract, start_date: datetime | str | None = None
) -> datetime | None:
    """
    Return datetime for the last available bar for given contract.

    start_date: how far back should available data be searched
    """
    if get_store() is None:
        return None
    else:
        df = get_store().read(contract, start_date=start_date)
        try:
            return df.iloc[-1].date  # type: ignore
        except (AttributeError, IndexError):
            return None


def bar_filter(bar: ibi.BarData) -> bool:
    """Return `true` if bar is faulty"""
    return any(
        (
            bar.close <= 0,
            bar.open <= 0,
            bar.high <= 0,
            bar.low <= 0,
            bar.average <= 0,
        )
    )


class Streamer(Atom, ABC):
    instances: ClassVar[list["Streamer"]] = []
    timeout: bool = True

    def __new__(cls, *args, **kwargs):
        # Keep track of all :class:`.Streamer` instances created so that they
        # can be re-started on reboot.
        obj = super().__new__(cls)
        cls.instances.append(obj)
        return obj

    @classmethod
    def awaitables(cls) -> list[Awaitable]:
        """
        Coroutines from all instantiated streamers.  Can be passed to
        :py:func:`asyncio.gather`
        """
        return [s.run() for s in cls.instances]

    @abstractmethod
    def streaming_func(self):
        raise NotImplementedError

    async def run(self) -> None:
        """
        Start subscription and start emitting data.  This is the main
        entry point into the streamer.
        """
        # this will check if contract changed and trigger
        # `onContractChanged` if necessary
        self.onStart({})
        ticker = self.streaming_func()
        ticker.updateEvent.clear()
        ticker.updateEvent += self.dataEvent
        self._set_timeout(ticker.updateEvent, "ticks")
        while self.ib.isConnected():
            await asyncio.sleep(0)

    def _set_timeout(self, event: ev.Event, name: str) -> None:
        """
        Automatically monitor event for stale data.  Can be switched
        off by overriding class variable `set_timeout`
        """
        if self.timeout:
            Timeout.from_atom(self, event, name)

    @cached_property
    def _id(self) -> int:
        return _counter()

    def __str__(self) -> str:
        identifier = [str(self._id)]
        if contract := getattr(self, "contract", None):
            identifier.append(contract.symbol)
        if name := getattr(self, "name", None):
            identifier.append(name)
        return f"{self.__class__.__name__}<{'><'.join(identifier)}>"


@dataclass
class HistoricalDataStreamer(Streamer):
    """
    Stream historical and realtime bars as generated by
    :meth:`ib_insync.IB.reqHistoricalDataAsync`

    Due to specifics of IB API, bars will be streamed with ca.  5
    seconds delay.  If this is not suitable for your strategy, use a
    different streamer (most likely you need
    :class:`TickByTickStreamer`).

    Args:
    -----

    * contract: ibi.Contract

    * durationStr: str | int - can be given as either a string
    acceptable by :meth:`ib_insync.IB.reqHistoricalDataAsync` or
    number of historical bars required (which will internally be
    converted to appropriate duration str)

    * barSizeSetting: str

    * whatToShow: str

    * useRTH: bool = False

    * formatDate: int = 2 - keeping the default 2 ensures timestamps
    will be returned as timeaware utc based; this is the only value
    that has been tested, other values may be incompatible with other
    framework components

    * read_db: bool = False - if True, before data request is made,
    last available datapoint will be ready from database and only
    newer data will be requested.

    * _last_bar_date: datetime | None = None - for internal use only,
    shouldn't be set manually


    Notes on the specifics of Interactive Brokers API:
    --------------------------------------------------

    The API does not stream data to a historical subscription; it
    broadcasts a snapshot of the database every 5 seconds.

        - Bars are timestamped at the start of the bar period

        - For bars with duration longer than 5 seconds:

            - last bar is always work in progress, it is still bound
              to be updated, it's not suitable for usage yet

            - Updates happen every 5 seconds, `hasNewBar` will be True
              only 5 seconds (+processing time, typically ca.  1 sec)
              after new bar is ready

            - There is no way to receive new bars immediately when
              they're created; it doesn't matter how `updateEvent` is
              accessed

        - 5 second bars behave the same as RealTimeBars:

            - `hasNewBar` is always True

            - last bar is immediately ready (API update period is the
              same as bar lenght so no reason)

        - Bars shorter than 5 seconds are not allowed
    """

    contract: ibi.Contract
    durationStr: str | int  # can be given as number of required datapoints
    barSizeSetting: str
    whatToShow: str
    useRTH: bool = False
    formatDate: int = 2  # should be 2 for utc timestamp
    read_db: bool = False  # should attempt be made to read last point from db
    _last_bar_date: datetime | None = None

    def __post_init__(self):
        Atom.__init__(self)

    def streaming_func(self) -> Awaitable:
        return self.ib.reqHistoricalDataAsync(
            self.contract,
            endDateTime="",
            durationStr=self._durationStr,
            barSizeSetting=self.barSizeSetting,
            whatToShow=self.whatToShow,
            useRTH=self.useRTH,
            formatDate=self.formatDate,
            keepUpToDate=True,
            timeout=0,
        )

    def _ensure_durationStr(self) -> str:
        """
        Accept durationStr as either ready str to be passed to
        :meth:`ib_insync.IB.reqHistoricalData` or if it's passed as a
        number of required datapoints int, convert it to the correct str.
        """
        return (
            datapoints_to_durationStr(
                self.durationStr,
                self.barSizeSetting,
                typical_session_length(self.contract_details.trading_hours),
            )
            if isinstance(self.durationStr, int)
            else self.durationStr
        )

    @property
    def _durationStr(self) -> str:
        return (
            date_to_delta_wrapper(self._last_bar_date, self.barSizeSetting, margin=2)
            if self._last_bar_date
            else self._ensure_durationStr()
        )

    async def last_bar_date(self) -> datetime | None:
        return self._last_bar_date or (
            (self.read_db and last_db_point(self.contract)) or None
        )

    async def run(self) -> None:
        self.onStart({})

        # this starts subscription so that current price is readily available from ib
        stream = self.ib.reqMktData(self.contract, "221")
        self._set_timeout(stream.updateEvent, "ticks")

        log.debug(f"{self!s} requesting bars {self._durationStr=}")
        bars = await self.streaming_func()
        log.debug(f"{self!s} received historical bars, last bar date: {bars[-1].date}")
        self._set_timeout(bars.updateEvent, "bars")

        try:
            async for bars_, hasNewBar in bars.updateEvent:
                if hasNewBar and (
                    (not self._last_bar_date) or (bars[-2].date > self._last_bar_date)
                ):
                    self._last_bar_date = bars_[-2].date
                    self.on_new_bar(bars_[:-1])
        except ValueError as e:
            log.debug(f"Empty emit for {self!s}: {e}")

    def on_new_bar(self, bars: ibi.BarDataList) -> None:
        if bar_filter(bars[-1]):
            return
        else:
            self.dataEvent.emit(bars)

    def onContractChanged(
        self, old_contract: ibi.Contract, new_contract: ibi.Contract
    ) -> None:
        self._last_bar_date = None
        super().onContractChanged(old_contract, new_contract)


@dataclass
class MktDataStreamer(Streamer):
    """Stream market data."""

    contract: ibi.Contract
    tickList: str

    def __post_init__(self):
        Atom.__init__(self)

    def streaming_func(self) -> ibi.Ticker:
        return self.ib.reqMktData(self.contract, self.tickList)


@dataclass
class RealTimeBarsStreamer(Streamer):
    """
    Stream realtime 5 seconds bars.

    Notes on the specifics of Interactive Brokers API:
    --------------------------------------------------

    - Bars are timestamped at the start of the bar period

    - The only possible bar interval is 5 seconds

    - Emits also happen every 5 seconds so `hasNewBar` is always True
      and the last bar is ready, i.e. it will not be adjusted
      subsequently

    - All bars including the last one are immediately usable

    """

    contract: ibi.Contract
    whatToShow: str
    useRTH: bool
    realTimeBarsOptions: list[ibi.TagValue] = field(default_factory=list)

    def __post_init__(self):
        Atom.__init__(self)

    def streaming_func(self):
        return self.ib.reqRealTimeBars(
            self.contract,
            5,
            self.whatToShow,
            self.useRTH,
        )

    async def run(self):
        """
        The difference to superclass is that here we connect the
        `updateEvent` to intermediary function `onUpdate`, which needs
        to perform some additional checks before emitting `dataEvent`.
        """
        self.onStart({})
        bars = self.streaming_func()
        bars.updateEvent.clear()
        bars.updateEvent += self.onUpdate
        self._set_timeout(bars.updateEvent, "bars")
        while self.ib.isConnected():
            await asyncio.sleep(0)

    def onUpdate(self, bars, hasNewBar):
        # No need to filter out the last bar
        # emits are every 5 secs, hasNewBar always True
        # last bar is ready and not modified after emit
        if hasNewBar and not bar_filter(bars[-1]):
            self.dataEvent.emit(bars)


@dataclass
class TickByTickStreamer(Streamer):
    """Stream tick by tick data."""

    contract: ibi.Contract
    tickType: str
    numberOfTicks: int = 0
    ignoreSize: bool = False

    def __post_init__(self):
        Atom.__init__(self)

    def streaming_func(self) -> ibi.Ticker:
        return self.ib.reqTickByTickData(
            contract=self.contract,
            tickType=self.tickType,
            numberOfTicks=self.numberOfTicks,
            ignoreSize=self.ignoreSize,
        )
