name: "Sphinx: Render docs"

on: 
  push:  # Trigger on all push events

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for writing to GitHub Pages
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .  # Installs haymaker package
        pip install -r docs/requirements.txt  # Installs Sphinx and its dependencies

    - name: Build HTML
      run: |
        cd docs
        sphinx-build -b html source build/html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'  # Only deploy when on master branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html